/* Auto-generated by genmsg_cpp for file /home/olegzilm/GoogleDrive/UT/code/Autonomous_Robots_CS393/amrl_libraries/amrl_msgs/msg/Point2D.msg */
#ifndef AMRL_MSGS_MESSAGE_POINT2D_H
#define AMRL_MSGS_MESSAGE_POINT2D_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace amrl_msgs
{
template <class ContainerAllocator>
struct Point2D_ {
  typedef Point2D_<ContainerAllocator> Type;

  Point2D_()
  : x(0.0)
  , y(0.0)
  {
  }

  Point2D_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  {
  }

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;


  typedef boost::shared_ptr< ::amrl_msgs::Point2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amrl_msgs::Point2D_<ContainerAllocator>  const> ConstPtr;
}; // struct Point2D
typedef  ::amrl_msgs::Point2D_<std::allocator<void> > Point2D;

typedef boost::shared_ptr< ::amrl_msgs::Point2D> Point2DPtr;
typedef boost::shared_ptr< ::amrl_msgs::Point2D const> Point2DConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::amrl_msgs::Point2D_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::amrl_msgs::Point2D_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace amrl_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::amrl_msgs::Point2D_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::amrl_msgs::Point2D_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::amrl_msgs::Point2D_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const  ::amrl_msgs::Point2D_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xff8d7d66dd3e4b73ULL;
  static const uint64_t static_value2 = 0x1ef14a45d38888b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::amrl_msgs::Point2D_<ContainerAllocator> > {
  static const char* value() 
  {
    return "amrl_msgs/Point2D";
  }

  static const char* value(const  ::amrl_msgs::Point2D_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::amrl_msgs::Point2D_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 x\n\
float32 y\n\
\n\
";
  }

  static const char* value(const  ::amrl_msgs::Point2D_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::amrl_msgs::Point2D_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::amrl_msgs::Point2D_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct Point2D_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amrl_msgs::Point2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::amrl_msgs::Point2D_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};


} // namespace message_operations
} // namespace ros

#endif // AMRL_MSGS_MESSAGE_POINT2D_H

